### ISSUE TITLE
Test bob.measure.test_error.test_plots fails on 32-bits Ubuntu Trusty

### ISSUE THREAD

**Issue by pkorshunov** [bioidiap/bob.measure#4]
It on 32-bits Ubuntu Trusty for sure, possibly, on the newer versions as well but it's not tested yet. The following assertion is violated:
assert numpy.array_equal(xy[1], ref)
Here is the complete buildlog with the failed test reported: 
https://launchpadlibrarian.net/229426116/buildlog_ubuntu-trusty-i386.bob.measure_2.0.5-0~ppa4~trusty1_BUILDING.txt.gz

I looked into the error a little and on 64-bits system, the call
xy = roc_for_far(negatives, positives, far)
results in xy[1]=[0.48, 0.22, 0] but on 32-bits system
xy[1]=[0.48, 0.12, 0]

**Comment by siebenkopf** [comment]
This looks like using outdated code (2.0.5), while this function has been re-implemented in 2.1.0 (the current master branch). I think, we need to update the package on PyPI as well. Hopefully that helps.

**Comment by pkorshunov** [comment]
@tiagofrepereira2012: do you think we can include the latest bob.measure to the meta Bob package? It seems it might allow us to have a correct build on Ubuntu 32-bits.

**Comment by siebenkopf** [comment]
I don't have a 32 bit machine here at hand. It would be interesting if you could check out, whether the tests pass on the current master branch... Just go to the machine, check out the latest master branch, build and run the nose tests.

**Comment by pkorshunov** [comment]
I just built the latest version from Git master branch on Ubuntu 12.04 23-bits and the test fails the same way, so the error is present in the latest version of bob.measure as well.

**Comment by tiagofrepereira2012** [comment]
Well, it seems that we have a some issues with 32 bits.
Questions for debate:
 1. Shall we still support 32 bits platform?
 2. If yes, I think it is a good idea to add VM with Ubuntu 32bits in our CI, what do you think?

PS: I'm installing a VM with Ubuntu 32 bits to reproduce this and other issues.

Thanks

**Comment by tiagofrepereira2012** [comment]
Just to complement, I think we should release the 2.1 version of this package independent of the 32bits issue.
With this update, the version of the package called bob must be updated for the version 2.1.0 too.

**Comment by tiagofrepereira2012** [comment]
I'm looking on this one

**Comment by tiagofrepereira2012** [comment]
Well, as already suspected, we have a precision error between platforms.

To sumarize the issue is in this line https://github.com/bioidiap/bob.measure/blob/master/bob/measure/cpp/error.cpp#L401

In the test case that fails, the code:
```if ((double)neg_index / (double)n_neg > 1. - far_list(far_index))```
compares 0.9 > 0.9 and for the 32 bits platform this returns ```True``` and this makes exit the loop in the line https://github.com/bioidiap/bob.measure/blob/master/bob/measure/cpp/error.cppL411

On the other hand, in the 64 bits platform this returns ```False```, which is correct as far as I remember my elementary school classes :-P

We have two options here:
 1 - Change the unit test and be happy
 2 - Do an additional test in this ```if```` with the method isclose from bob.core 

What do you think people?

**Comment by siebenkopf** [comment]
Hmm... I thought that the ``double`` would be the same between 32 and 64 bit machines. So, where does that difference come from? Can anyone enlighten me, what could cause the difference here?

One reason that might be is that the python ``float`` evaluates to C++ ``float`` on 32 bit machines and ``double`` in 64 bit machines, but I doubt that this is really the case... (AFAIR, we use ``double`` in the bindings).

**Comment by anjos** [comment]
Calculations involving double's on a 32-bit machine may be differently encoded than that on a 64-bit one, mainly due to the way the compiler will write the final assembly code. As can be expected, this is highly dependent on the architecture. Some insight:

http://stackoverflow.com/questions/22710272/difference-in-floating-point-arithmetics-between-x86-and-x64

**Comment by tiagofrepereira2012** [comment]
Yeap, if you cast to single precision it works.

**Comment by tiagofrepereira2012** [comment]
Solved with the commit a827995

**Comment by siebenkopf** [comment]
After reading the page that @anjos provided, it would have been easier to assign ``(double)neg_index / (double)n_neg`` (maybe and  ``1. - far_list(far_index)``) in 
https://github.com/bioidiap/bob.measure/blob/master/bob/measure/cpp/error.cpp#L403
to variables before comparison. Also, there is a similar comparison in:
https://github.com/bioidiap/bob.measure/blob/master/bob/measure/cpp/error.cpp#L426
which should be updated with the same solution.
